# Generated by Django 4.2.8 on 2023-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_district_code_customuser_district_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
